#!/bin/sh

TESTS=" \
execstack_run_with-s \
execstack_run_with-c \
execstack_run_version \
execstack_run_help \
execstack_run_usage \
"

for tst in $TESTS; do
	if ./$tst; then
		echo "PASS: $tst"
	else
		echo "FAIL: $tst"
	fi
done
