#!/bin/sh

TESTS=" \
run_version_command \
run_help_command \
run_list_command \
run_static_nodes_command \
"

for tst in $TESTS; do
    if ./$tst; then
       echo "PASS: $tst"
    else
       echo "FAIL: $tst"
    fi
done
