# This is generated by debian-source.bbclass
DPV = "1.8.2-1"
DPV_EPOCH = ""
REPACK_PV = "1.8.2"
PV = "1.8.2"

DEBIAN_SRC_URI = " \
    ${DEBIAN_MIRROR}/main/n/ninja-build/ninja-build_1.8.2-1.dsc;name=ninja-build_1.8.2-1.dsc \
    ${DEBIAN_MIRROR}/main/n/ninja-build/ninja-build_1.8.2.orig.tar.gz;name=ninja-build_1.8.2.orig.tar.gz \
    ${DEBIAN_MIRROR}/main/n/ninja-build/ninja-build_1.8.2-1.debian.tar.xz;name=ninja-build_1.8.2-1.debian.tar.xz \
"

SRC_URI[ninja-build_1.8.2-1.dsc.md5sum] = "4e3a796843471c91f7f4a9ad138d3af3"
SRC_URI[ninja-build_1.8.2.orig.tar.gz.md5sum] = "5fdb04461cc7f5d02536b3bfc0300166"
SRC_URI[ninja-build_1.8.2-1.debian.tar.xz.md5sum] = "b79249f31b84bb6713dea5b2213643cc"

SRC_URI[ninja-build_1.8.2-1.dsc.sha256sum] = "43ec713a1fa29e19cb822ba005d24c895452c004845439093dce1c2704cf680e"
SRC_URI[ninja-build_1.8.2.orig.tar.gz.sha256sum] = "86b8700c3d0880c2b44c2ff67ce42774aaf8c28cbf57725cb881569288c1c6f4"
SRC_URI[ninja-build_1.8.2-1.debian.tar.xz.sha256sum] = "b19f943eb7054a244a706e8f95b5c85081f28081871ef72b7ca0bce1bacb4145"
