#!/bin/sh

TESTS=" \
run_create_table \
run_insert_record \
run_view_record \
run_alter_tablename \
run_drop_table \
run_version_command \
"

for tst in $TESTS; do
	if ./$tst; then
		echo "PASS: $tst"
	else
		echo "FAIL: $tst"
	fi
done
