#!/bin/sh

TESTS=" \
run_checksig_command \
run_checkdepend_command \
run_get_info_command \
run_help_command \
run_usage_command \
"

for tst in $TESTS; do
	if ./$tst; then
		echo "PASS: $tst"
	else
		echo "FAIL: $tst"
	fi
done
