#!/bin/sh

TESTS=" \
run_file_without_options \
run_file_with_options-E \
run_file_with_options-i \
run_file_with_options-P \
run_file_with_options-Q \
run_help_command \
run_version_command \
"

for tst in $TESTS; do
	if ./$tst; then
		echo "PASS: $tst"
	else
		echo "FAIL: $tst"
	fi
done
