# provider for debian distro
PREFERRED_PROVIDER_make-native = "make-native"
PREFERRED_PROVIDER_virtual/kernel = "linux-base"
PREFERRED_PROVIDER_linux-libc-headers = "linux-libc-headers-base"
PREFERRED_PROVIDER_virtual/update-alternatives = "dpkg-update-alternatives"
PREFERRED_PROVIDER_virtual/update-alternatives-native = "dpkg-update-alternatives-native"
PREFERRED_PROVIDER_python-argparse = "python"
VIRTUAL-RUNTIME_update-alternatives = ""
