#!/bin/bash

clean_up()
{
    unset BUILDDIR REPOS
}

# save error during 'source setup-emlinux'
_ERROR=0
trap '_ERROR=$?' ERR

BUILDDIR="build"
if [ -n "$1" ]; then
    BUILDDIR=$1
fi

sudo apt-get update
sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping libsdl1.2-dev xterm

REPOS=${PWD}/repos
if [ ! -d ${REPOS}/poky ]; then
    git clone -b master https://git.yoctoproject.org/git/poky ${REPOS}/poky
fi
if [ ! -d ${REPOS}/meta-debian ]; then
    git clone -b master \
	https://github.com/meta-debian/meta-debian.git ${REPOS}/meta-debian
fi
if [ ! -d ${REPOS}/meta-debian-extended ]; then
    git clone -b master \
	https://github.com/miraclelinux/meta-debian-extended.git \
	${REPOS}/meta-debian-extended
fi

source ${REPOS}/poky/oe-init-build-env ${BUILDDIR}

# delete layer
bitbake-layers remove-layer meta-poky
bitbake-layers remove-layer meta-yocto-bsp

# add layer
bitbake-layers add-layer ${REPOS}/meta-debian
bitbake-layers add-layer ${REPOS}/meta-debian-extended
bitbake-layers add-layer ${REPOS}/meta-emlinux

# Add config
echo "DISTRO = \"emlinux\"" >> conf/local.conf
echo "PACKAGE_CLASSES = \"package_deb\"" >> conf/local.conf
echo "BBMASK = \"meta-debian/recipes-core\"" >> conf/local.conf
echo "BBMASK .= \"|meta-debian-extended/recipes-debian/base-files/base-files_debian.bb\"" >> conf/local.conf
echo "DEBIAN_SOURCE_ENABLED = \"1\"" >> conf/local.conf

clean_up
if [ $_ERROR -ne 0 ]; then
    echo "ERROR: an error occured during setup ($_ERROR)"
fi
return $_ERROR
