#!/bin/bash

BUILDDIR="build"
if [ -n "$1" ]; then
    BUILDDIR=$1
fi

sudo apt-get update
sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping libsdl1.2-dev xterm

git clone -b master https://git.yoctoproject.org/git/poky ${PWD}/poky
git clone -b master https://github.com/meta-debian/meta-debian.git ${PWD}/meta-debian
git clone -b master https://github.com/iwamatsu/meta-debian-extended.git ${PWD}/meta-debian-extended

source ${PWD}/poky/oe-init-build-env ${BUILDDIR}

# delete layer
bitbake-layers remove-layer meta-poky
bitbake-layers remove-layer meta-yocto-bsp

# add layer
bitbake-layers add-layer ../meta-debian
bitbake-layers add-layer ../meta-debian-extended
bitbake-layers add-layer ../meta-emlinux

# Add config
echo "DISTRO = \"emlinux\"" >> conf/local.conf
echo "PACKAGE_CLASSES = \"package_deb\"" >> conf/local.conf
echo "BBMASK = \"meta-debian/recipes-core\"" >> conf/local.conf
echo "BBMASK .= \"|meta-debian-extended/recipes-debian/base-files/base-files_debian.bb\"" >> conf/local.conf
