#!/bin/bash

clean_up()
{
    unset BUILDDIR BUILDDIR_SETUP_DONE REPOS
}

# save error during 'source setup-emlinux'
_ERROR=0
trap '_ERROR=$?' ERR

BUILDDIR="build"
if [ -n "$1" ]; then
    BUILDDIR=$1
fi

BUILDDIR_SETUP_DONE="true"
if [ ! -e ${BUILDDIR}/conf/local.conf ]; then
    BUILDDIR_SETUP_DONE="false"
fi

REPOS=${PWD}/repos
if [ ! -d ${REPOS}/poky ]; then
    git clone -b warrior https://git.yoctoproject.org/git/poky ${REPOS}/poky
fi
if [ ! -d ${REPOS}/meta-debian ]; then
    git clone -b warrior \
	https://github.com/meta-debian/meta-debian.git ${REPOS}/meta-debian
fi
if [ ! -d ${REPOS}/meta-debian-extended ]; then
    git clone -b warrior \
	https://github.com/miraclelinux/meta-debian-extended.git \
	${REPOS}/meta-debian-extended
fi

source ${REPOS}/poky/oe-init-build-env ${BUILDDIR}

if [ "${BUILDDIR_SETUP_DONE}" = "false" ]; then
    # delete layer
    bitbake-layers remove-layer meta-poky
    bitbake-layers remove-layer meta-yocto-bsp

    # add layer
    bitbake-layers add-layer ${REPOS}/meta-debian
    bitbake-layers add-layer ${REPOS}/meta-debian-extended
    bitbake-layers add-layer ${REPOS}/meta-emlinux

    # Add config
    echo "DISTRO = \"emlinux\"" >> conf/local.conf
    echo "PACKAGE_CLASSES = \"package_deb\"" >> conf/local.conf
    echo "BBMASK = \"meta-debian/recipes-core\"" >> conf/local.conf
    echo "BBMASK .= \"|meta-debian-extended/recipes-debian/base-files/base-files_debian.bb\"" >> conf/local.conf
    echo "DL_DIR = \"\${TOPDIR}/../downloads\"" >> conf/local.conf
fi

clean_up
if [ $_ERROR -ne 0 ]; then
    echo "ERROR: an error occured during setup ($_ERROR)"
fi
return $_ERROR
