#!/bin/bash

REPOS=${PWD}/repos
for r in poky meta-debian meta-debian-extended; do
    if [ -e ${REPOS}/$r ] ; then
        echo "$r remote update, and merge"
        cd $r; git remote update; git merge origin/warrior
    fi
done
