#!/bin/sh

TESTS=" \
run_modversion_command \
run_libs_command \
run_cflags_command \
"

export PKG_CONFIG_PATH=$PWD

for tst in $TESTS; do
	if ./$tst; then
		echo "PASS: $tst"
	else
		echo "FAIL: $tst"
	fi
done
