#!/bin/sh
#
# minimal bootup script to mount file systems
#
# required features:
#   kernel: PROC_FS, UNIX98_PTYS, SYSFS, DEVTMPFS, DEVTMPFS_MOUNT=n
#   busybox: sh, mount, mkdir
#

mount none -t proc /proc
mount none -t sysfs /sys

mount none -t devtmpfs /dev

mkdir /dev/pts
mount none -t devpts /dev/pts
