#!/bin/sh
#
# tiny-init
#
# This script is almost same as poky's tiny-init except network settings
# required features:
#   kernel: PROC_FS, UNIX98_PTYS, SYSFS, DEVTMPFS, DEVTMPFS_MOUNT=n
#   busybox: sh, mount, mkdir, true, setsid, cttyhack, echo, sleep
#

# Mount the Linux kernel virtual filesystems
mount none -t proc /proc
mount none -t sysfs /sys

# Ensure devtmpfs is mounted, it must be done manually with initramfs
mount none -t devtmpfs /dev

# Setup PTY infrastructure
mkdir /dev/pts
mount none -t devpts /dev/pts

# Allow for distro or local customizations
if [ -f /etc/rc.local ] ; then
	. /etc/rc.local
fi

# Become session leader and try to find a real tty (e.g. ttyS0)
while true; do
	setsid cttyhack sh
	echo "Console sh exited with $?, respawning..."
	sleep 1
done
