#!/bin/sh

TESTS=" \
run_version_command \
run_help_command \
run_cipher_command \
run_speed_command \
run_certificate_command \
"

for tst in $TESTS; do
	if ./$tst; then
		echo "PASS: $tst"
	else
		echo "FAIL: $tst"
	fi
done
